### PR TITLE
Pre/post processing improvements

### PR DESCRIPTION
**Pull request by zachlipton**
- Run standardize_data and post_processing on all states, including those not previously included in _FUNCTION_LISTS
- Remove newlines from facility names
- Post-process all states to fill in missing dates and sort
- When filling missing dates, only copy cumulative data, not outbreak data
- Sort all output by facility and date

### CODE REVIEW

**Comment by zachlipton** [comment]
My biggest concern here is that applying`fill_missing_dates` to all states may have unintended consequences due to anomalies in a number of states. I'm running it now and will report back with a list.

Also, I'll unbreak the tests.

**Comment by julia326** [comment]
this looks perfect!! Thank you so much - feel free to merge when you're confident that `fill_missing_dates` doesn't do anything weird in practice

**Review by julia326 — APPROVED** [review]

**Comment by zachlipton** [comment]
This is all the missing data that gets filled in. Some are real missing weeks, but I've put the ones that seem particularly suspicious or erroneous in bold with some annotations added. There are a number of states that didn't follow the once-every-Thursday collection pattern, and this function doesn't really deal with that, but I'm not sure how much that's a problem.


AR: 
I2021-02-22 18:43:09,016 [fill_missing_dates.py:31] Missing data for 20200618. Backfilling cumulative data from 20200611
I2021-02-22 18:43:09,123 [fill_missing_dates.py:31] Missing data for 20201203. Backfilling cumulative data from 20201126

CT:
I2021-02-22 18:46:10,658 [fill_missing_dates.py:31] Missing data for 20201231. Backfilling cumulative data from 20201224

DE:
I2021-02-22 18:46:25,516 [fill_missing_dates.py:31] Missing data for 20200806. Backfilling cumulative data from 20200730
I2021-02-22 18:46:25,538 [fill_missing_dates.py:31] Missing data for 20201210. Backfilling cumulative data from 20201203

FL:
**I2021-02-22 18:57:14,667 [fill_missing_dates.py:31] Missing data for 20201126. Backfilling cumulative data from 20201125**

HI: 
I2021-02-22 18:57:49,022 [fill_missing_dates.py:31] Missing data for 20201001. Backfilling cumulative data from 20200924
I2021-02-22 18:57:49,063 [fill_missing_dates.py:31] Missing data for 20201112. Backfilling cumulative data from 20201105
I2021-02-22 18:57:49,082 [fill_missing_dates.py:31] Missing data for 20201126. Backfilling cumulative data from 20201119
I2021-02-22 18:57:49,114 [fill_missing_dates.py:31] Missing data for 20201231. Backfilling cumulative data from 20201224

IA: 
I2021-02-22 18:58:24,619 [fill_missing_dates.py:31] Missing data for 20200827. Backfilling cumulative data from 20200820
I2021-02-22 18:58:24,643 [fill_missing_dates.py:31] Missing data for 20200924. Backfilling cumulative data from 20200917

ID: 
I2021-02-22 18:58:26,159 [fill_missing_dates.py:31] Missing data for 20200709. Backfilling cumulative data from 20200702
I2021-02-22 18:58:26,163 [fill_missing_dates.py:31] Missing data for 20200716. Backfilling cumulative data from 20200702
**I2021-02-22 18:58:26,167 [fill_missing_dates.py:31] Missing data for 20200723. Backfilling cumulative data from 20200702** [data exists for 20200724 but not 20200723]
**I2021-02-22 18:58:26,171 [fill_missing_dates.py:31] Missing data for 20200730. Backfilling cumulative data from 20200724** [data exists for 20200731]
**I2021-02-22 18:58:26,176 [fill_missing_dates.py:31] Missing data for 20200806. Backfilling cumulative data from 20200731**
**I2021-02-22 18:58:26,180 [fill_missing_dates.py:31] Missing data for 20200813. Backfilling cumulative data from 20200807
I2021-02-22 18:58:26,185 [fill_missing_dates.py:31] Missing data for 20200820. Backfilling cumulative data from 20200814**
**I2021-02-22 18:58:26,190 [fill_missing_dates.py:31] Missing data for 20200903. Backfilling cumulative data from 20200827**
**I2021-02-22 18:58:26,195 [fill_missing_dates.py:31] Missing data for 20200910. Backfilling cumulative data from 20200904
I2021-02-22 18:58:26,200 [fill_missing_dates.py:31] Missing data for 20200917. Backfilling cumulative data from 20200911**

ME:
I2021-02-22 19:03:21,649 [fill_missing_dates.py:31] Missing data for 20201015. Backfilling cumulative data from 20201008
I2021-02-22 19:03:21,653 [fill_missing_dates.py:31] Missing data for 20201105. Backfilling cumulative data from 20201029
I2021-02-22 19:03:21,660 [fill_missing_dates.py:31] Missing data for 20201231. Backfilling cumulative data from 20201224
I2021-02-22 19:03:21,663 [fill_missing_dates.py:31] Missing data for 20210114. Backfilling cumulative data from 20210107

MI:
I2021-02-22 19:03:31,486 [fill_missing_dates.py:31] Missing data for 20200521. Backfilling cumulative data from 20200515
**I2021-02-22 19:03:31,494 [fill_missing_dates.py:31] Missing data for 20200528. Backfilling cumulative data from 20200515** [20200827 exists]
I2021-02-22 19:03:31,511 [fill_missing_dates.py:31] Missing data for 20200903. Backfilling cumulative data from 20200827
I2021-02-22 19:03:31,525 [fill_missing_dates.py:31] Missing data for 20201029. Backfilling cumulative data from 20201022

MN: 
I2021-02-22 19:03:56,404 [fill_missing_dates.py:31] Missing data for 20200924. Backfilling cumulative data from 20200917

MO: 
I2021-02-22 19:04:08,272 [fill_missing_dates.py:31] Missing data for 20200702. Backfilling cumulative data from 20200625
I2021-02-22 19:04:08,276 [fill_missing_dates.py:31] Missing data for 20200709. Backfilling cumulative data from 20200625
I2021-02-22 19:04:08,279 [fill_missing_dates.py:31] Missing data for 20200716. Backfilling cumulative data from 20200625
I2021-02-22 19:04:08,282 [fill_missing_dates.py:31] Missing data for 20200723. Backfilling cumulative data from 20200625
I2021-02-22 19:04:08,286 [fill_missing_dates.py:31] Missing data for 20200806. Backfilling cumulative data from 20200730
I2021-02-22 19:04:08,290 [fill_missing_dates.py:31] Missing data for 20200813. Backfilling cumulative data from 20200730
I2021-02-22 19:04:08,293 [fill_missing_dates.py:31] Missing data for 20200820. Backfilling cumulative data from 20200730
I2021-02-22 19:04:08,297 [fill_missing_dates.py:31] Missing data for 20200903. Backfilling cumulative data from 20200827
I2021-02-22 19:04:08,301 [fill_missing_dates.py:31] Missing data for 20200910. Backfilling cumulative data from 20200827
I2021-02-22 19:04:08,304 [fill_missing_dates.py:31] Missing data for 20200917. Backfilling cumulative data from 20200827
I2021-02-22 19:04:08,308 [fill_missing_dates.py:31] Missing data for 20201001. Backfilling cumulative data from 20200924
I2021-02-22 19:04:08,311 [fill_missing_dates.py:31] Missing data for 20201008. Backfilling cumulative data from 20200924
I2021-02-22 19:04:08,315 [fill_missing_dates.py:31] Missing data for 20201015. Backfilling cumulative data from 20200924
I2021-02-22 19:04:08,319 [fill_missing_dates.py:31] Missing data for 20201022. Backfilling cumulative data from 20200924
I2021-02-22 19:04:08,324 [fill_missing_dates.py:31] Missing data for 20201105. Backfilling cumulative data from 20201029
I2021-02-22 19:04:08,327 [fill_missing_dates.py:31] Missing data for 20201112. Backfilling cumulative data from 20201029
I2021-02-22 19:04:08,330 [fill_missing_dates.py:31] Missing data for 20201119. Backfilling cumulative data from 20201029
I2021-02-22 19:04:08,334 [fill_missing_dates.py:31] Missing data for 20201203. Backfilling cumulative data from 20201126
I2021-02-22 19:04:08,337 [fill_missing_dates.py:31] Missing data for 20201210. Backfilling cumulative data from 20201126
I2021-02-22 19:04:08,340 [fill_missing_dates.py:31] Missing data for 20201217. Backfilling cumulative data from 20201126
I2021-02-22 19:04:08,343 [fill_missing_dates.py:31] Missing data for 20201224. Backfilling cumulative data from 20201126
I2021-02-22 19:04:08,348 [fill_missing_dates.py:31] Missing data for 20210121. Backfilling cumulative data from 20210114
I2021-02-22 19:04:08,352 [fill_missing_dates.py:31] Missing data for 20210128. Backfilling cumulative data from 20210114
I2021-02-22 19:04:08,356 [fill_missing_dates.py:31] Missing data for 20210218. Backfilling cumulative data from 20210211

MS:
I2021-02-22 19:04:19,962 [fill_missing_dates.py:31] Missing data for 20200611. Backfilling cumulative data from 20200604
I2021-02-22 19:04:19,967 [fill_missing_dates.py:31] Missing data for 20200702. Backfilling cumulative data from 20200625
I2021-02-22 19:04:19,970 [fill_missing_dates.py:31] Missing data for 20200709. Backfilling cumulative data from 20200625
I2021-02-22 19:04:19,978 [fill_missing_dates.py:31] Missing data for 20201008. Backfilling cumulative data from 20201001
I2021-02-22 19:04:19,982 [fill_missing_dates.py:31] Missing data for 20201015. Backfilling cumulative data from 20201001
I2021-02-22 19:04:19,985 [fill_missing_dates.py:31] Missing data for 20201022. Backfilling cumulative data from 20201001
I2021-02-22 19:04:19,988 [fill_missing_dates.py:31] Missing data for 20201029. Backfilling cumulative data from 20201001
I2021-02-22 19:04:19,992 [fill_missing_dates.py:31] Missing data for 20201105. Backfilling cumulative data from 20201001
I2021-02-22 19:04:19,995 [fill_missing_dates.py:31] Missing data for 20201112. Backfilling cumulative data from 20201001
I2021-02-22 19:04:19,998 [fill_missing_dates.py:31] Missing data for 20201119. Backfilling cumulative data from 20201001
I2021-02-22 19:04:20,002 [fill_missing_dates.py:31] Missing data for 20201126. Backfilling cumulative data from 20201001
I2021-02-22 19:04:20,005 [fill_missing_dates.py:31] Missing data for 20201203. Backfilling cumulative data from 20201001
I2021-02-22 19:04:20,009 [fill_missing_dates.py:31] Missing data for 20201210. Backfilling cumulative data from 20201001
I2021-02-22 19:04:20,012 [fill_missing_dates.py:31] Missing data for 20201217. Backfilling cumulative data from 20201001
I2021-02-22 19:04:20,016 [fill_missing_dates.py:31] Missing data for 20201224. Backfilling cumulative data from 20201001
I2021-02-22 19:04:20,019 [fill_missing_dates.py:31] Missing data for 20201231. Backfilling cumulative data from 20201001
I2021-02-22 19:04:20,022 [fill_missing_dates.py:31] Missing data for 20210107. Backfilling cumulative data from 20201001
I2021-02-22 19:04:20,026 [fill_missing_dates.py:31] Missing data for 20210114. Backfilling cumulative data from 20201001
I2021-02-22 19:04:20,029 [fill_missing_dates.py:31] Missing data for 20210121. Backfilling cumulative data from 20201001
I2021-02-22 19:04:20,033 [fill_missing_dates.py:31] Missing data for 20210128. Backfilling cumulative data from 20201001
I2021-02-22 19:04:20,036 [fill_missing_dates.py:31] Missing data for 20210204. Backfilling cumulative data from 20201001
I2021-02-22 19:04:20,040 [fill_missing_dates.py:31] Missing data for 20210218. Backfilling cumulative data from 20210211


NM:
I2021-02-22 19:09:22,364 [fill_missing_dates.py:31] Missing data for 20200528. Backfilling cumulative data from 20200521
I2021-02-22 19:09:22,378 [fill_missing_dates.py:31] Missing data for 20200604. Backfilling cumulative data from 20200521
I2021-02-22 19:09:22,494 [fill_missing_dates.py:31] Missing data for 20201126. Backfilling cumulative data from 20201119
I2021-02-22 19:09:22,528 [fill_missing_dates.py:31] Missing data for 20201231. Backfilling cumulative data from 20201224
I2021-02-22 19:09:22,547 [fill_missing_dates.py:31] Missing data for 20210107. Backfilling cumulative data from 20201224

NV:
I2021-02-22 19:09:34,658 [fill_missing_dates.py:31] Missing data for 20210121. Backfilling cumulative data from 20210114

OH:
I2021-02-22 19:10:09,537 [fill_missing_dates.py:31] Missing data for 20201126. Backfilling cumulative data from 20201125

OK:
I2021-02-22 19:10:11,833 [fill_missing_dates.py:31] Missing data for 20200730. Backfilling cumulative data from 20200723
I2021-02-22 19:10:11,858 [fill_missing_dates.py:31] Missing data for 20201217. Backfilling cumulative data from 20201210

OR:
**I2021-02-22 19:10:58,992 [fill_missing_dates.py:31] Missing data for 20200625. Backfilling cumulative data from 20200624**
I2021-02-22 19:10:59,000 [fill_missing_dates.py:31] Missing data for 20200716. Backfilling cumulative data from 20200709
**I2021-02-22 19:10:59,019 [fill_missing_dates.py:31] Missing data for 20201126. Backfilling cumulative data from 20201125**
**I2021-02-22 19:10:59,027 [fill_missing_dates.py:31] Missing data for 20201203. Backfilling cumulative data from 20201202**

PA:
**I2021-02-22 19:11:02,140 [fill_missing_dates.py:31] Missing data for 20200611. Backfilling cumulative data from 20200608**
**I2021-02-22 19:11:02,157 [fill_missing_dates.py:31] Missing data for 20200820. Backfilling cumulative data from 20200817**
**I2021-02-22 19:11:02,165 [fill_missing_dates.py:31] Missing data for 20200827. Backfilling cumulative data from 20200824**

RI:
I2021-02-22 19:11:15,057 [fill_missing_dates.py:31] Missing data for 20200702. Backfilling cumulative data from 20200625
I2021-02-22 19:11:15,062 [fill_missing_dates.py:31] Missing data for 20200716. Backfilling cumulative data from 20200709

TX [aready fixed 20201217]:
I2021-02-22 19:12:54,481 [fill_missing_dates.py:31] Missing data for 20201210. Backfilling cumulative data from 20201203
I2021-02-22 19:12:54,500 [fill_missing_dates.py:31] Missing data for 20201224. Backfilling cumulative data from 20201217
I2021-02-22 19:12:54,524 [fill_missing_dates.py:31] Missing data for 20210204. Backfilling cumulative data from 20210128

VA: 
**I2021-02-22 19:14:51,608 [fill_missing_dates.py:31] Missing data for 20201105. Backfilling cumulative data from 20201102**
**I2021-02-22 19:14:51,613 [fill_missing_dates.py:31] Missing data for 20201112. Backfilling cumulative data from 20201109**
**I2021-02-22 19:14:51,618 [fill_missing_dates.py:31] Missing data for 20201119. Backfilling cumulative data from 20201116**
**I2021-02-22 19:14:51,623 [fill_missing_dates.py:31] Missing data for 20201126. Backfilling cumulative data from 20201125**

WV:
I2021-02-22 19:15:10,094 [fill_missing_dates.py:31] Missing data for 20200625. Backfilling cumulative data from 20200618
I2021-02-22 19:15:10,099 [fill_missing_dates.py:31] Missing data for 20200702. Backfilling cumulative data from 20200618
I2021-02-22 19:15:10,103 [fill_missing_dates.py:31] Missing data for 20200716. Backfilling cumulative data from 20200709
I2021-02-22 19:15:10,107 [fill_missing_dates.py:31] Missing data for 20200723. Backfilling cumulative data from 20200717
I2021-02-22 19:15:10,120 [fill_missing_dates.py:31] Missing data for 20210107. Backfilling cumulative data from 20201231

WY:
I2021-02-22 19:15:14,454 [fill_missing_dates.py:31] Missing data for 20200903. Backfilling cumulative data from 20200827
I2021-02-22 19:15:14,458 [fill_missing_dates.py:31] Missing data for 20200910. Backfilling cumulative data from 20200827
I2021-02-22 19:15:14,463 [fill_missing_dates.py:31] Missing data for 20201105. Backfilling cumulative data from 20201029
I2021-02-22 19:15:14,467 [fill_missing_dates.py:31] Missing data for 20201126. Backfilling cumulative data from 20201119
I2021-02-22 19:15:14,472 [fill_missing_dates.py:31] Missing data for 20201224. Backfilling cumulative data from 20201217
I2021-02-22 19:15:14,476 [fill_missing_dates.py:31] Missing data for 20210128. Backfilling cumulative data from 20210121
I2021-02-22 19:15:14,480 [fill_missing_dates.py:31] Missing data for 20210211. Backfilling cumulative data from 20210204

**Comment by zachlipton** [comment]
I fixed the test. One thing just to flag is that because the outbreak status is not being backfilled, it can appear and disappear, e.g.:

```
20200716,COOL-STATE,,,nursing-home-1,Nursing Home,Nursing Home,Federal,, ,,,Open,,9,,9,,9,,,,,,,,,,,,,,,,,,,,,,,
20200723,COOL-STATE,,,nursing-home-1,Nursing Home,Nursing Home,Federal,, ,,,,,9,,9,,9,,,,,,,,,,,,,,,,,,,,,,,
20200730,COOL-STATE,,,nursing-home-1,Nursing Home,Nursing Home,Federal,, ,,,Open,,11,,11,,11,,,,,,,,,,,,,,,,,,,,,,,
```

**Pull request merged**
